apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pos-frontend
  namespace: production
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - pos-frontend.prpo.timhrovat.com
    secretName: pos-frontend-tls
  rules:
  - host: pos-frontend.prpo.timhrovat.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pos-frontend
            port:
              number: 80
